<?php $storeId = Mage::app()->getStore()->getId(); ?>
<?php $carriers = $this->getCarriers(); ?>

<?php if(Mage::getStoreConfig('coolrunner/settings/show_logos', $storeId)): ?>

	<?php foreach($carriers as $carrier): ?>
	
		<?php $logoUrl = $this->getSkinUrl('coolrunner/images/' . $carrier . '.png'); ?>
		
		<script type="text/javascript">
		
			coolrunner_<?php echo $carrier;?>_logos = {
								
				start : function() {
					coolrunner_<?php echo $carrier; ?>_logos.setLogos();
				},
				
				setLogos : function() {
					coolrunner_<?php echo $carrier; ?>_logos.setLogoAsBullets();
				},	
				
				setLogoAsBullets : function() {
					
					$$('label[for^=s_method_coolrunner_'+'<?php echo $carrier;?>'+']').each(function(value) {
						$(value).insert({
							top: '<img width="50" style="margin-right:6px;display:inline-block;vertical-align: top;" src="<?php echo $logoUrl;?>"/>'
						})
					});
		
				}
				
			}
			coolrunner_<?php echo $carrier;?>_logos.start();
		
		</script>
	
	<?php endforeach; ?>
	
<?php endif; ?>