<?php if(Mage::getStoreConfig('coolrunner/settings/active')) : ?>
	<script type="text/javascript">
		coolrunner = new CoolRunner();
		coolrunner.orderGridPostUrl = '<?php echo Mage::helper('adminhtml')->getUrl('coolrunner/adminhtml_grid/labelsForOrders'); ?>';
		coolrunner.orderInfoPostUrl = '<?php echo Mage::helper('adminhtml')->getUrl('coolrunner/adminhtml_grid/orderinfo'); ?>';
		coolrunner.orderPackageLabelDownloadUrl = '<?php echo Mage::helper('adminhtml')->getUrl('coolrunner/adminhtml_grid/downloadPdf'); ?>';
		<?php if($order = Mage::registry('current_order')) : ?>
			coolrunner.order_id = <?php echo $order->getId(); ?>;
		<?php else : ?>
			coolrunner.order_id = false;
		<?php endif; ?>
		coolrunner.start();
	</script>
<?php endif; ?>